// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcGqznF-tWF8U_rGmaF8bp-Iq2FyQmUMk',
    appId: '1:699973862074:web:91c8f621612e85b9fb7883',
    messagingSenderId: '699973862074',
    projectId: 'ecom-e7547',
    authDomain: 'ecom-e7547.firebaseapp.com',
    storageBucket: 'ecom-e7547.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ7yI69PpUzsWfVYGG04_dSh36a-BxzYs',
    appId: '1:699973862074:android:97bbd746148a5884fb7883',
    messagingSenderId: '699973862074',
    projectId: 'ecom-e7547',
    storageBucket: 'ecom-e7547.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCT3WeMfqBChNEheGz1Mu01SuGsDY8lcA',
    appId: '1:699973862074:ios:8f3b125c0c372c75fb7883',
    messagingSenderId: '699973862074',
    projectId: 'ecom-e7547',
    storageBucket: 'ecom-e7547.appspot.com',
    iosBundleId: 'com.example.eCom',
  );
}
